### ISSUE TITLE
Carbs / Fiber

### ISSUE THREAD

**Issue by clynham** [ryanashcraft/restaurant-nutrition-data#13]
Hi @ryanashcraft - Decided I'd have a go at formatting Greggs data which is one of the larger UK fast food chains and I don't think should cause too much confusion for US users as I don't think it's made it that side of the pond yet.

Source Data Is Here: https://www.greggs.co.uk/nutrition

Which links to: https://a.storyblok.com/f/94904/x/04ce652624/greggs-nutrition-information-sept-2022.pdf

I'll include the PDF in the sources directory. My question is about the Fibre values though. In the UK they're usually reported separately to carbs. I know the app can handle that difference but how should it be handled in the CSV upload. Should I add them into the carb figure which would then make the CSV file differ from the PDF or keep them the same?

This is the work in progress: https://github.com/clynham/restaurant-nutrition-data/blob/greggs-apr2023/greggs.csv

**Comment by ryanashcraft** [comment]
@clynham Good question. I should make this clear in the README. Please add the fiber amounts to the carbohydrates for cases like this where the listed carbohydrates exclude fiber.

**Comment by clynham** [comment]
Awesome, thanks. I'll submit a PR so you can have a look
