### ISSUE TITLE
International Restaurants

### ISSUE THREAD

**Issue by benjohnson** [ryanashcraft/restaurant-nutrition-data#6]
Is there a specific way you'd like us to handle international restaurants? I'm specifically thinking of Freshii and Tim Hortons who have different information for each country.

**Comment by ryanashcraft** [comment]
@benjohnson I'm still figuring out how to best handle this. I need to come up with a solution on the app/database side. For Freshii and Tim Hortons, I will probably simply postfix "(Canada)" in the brand name for now. e.g. "Tim Hortons (Canada)". Eventually I'll need to make things more complex, likely by introducing a "preferred region" database setting. Any thoughts from your perspective on how you'd like to see this handled in the app?

**Comment by benjohnson** [comment]
Yeah, the app part is definitely the hard part. Here's my thinking, take it or leave it :P

1. Have some organisational structure or file that connects these CSV files to ISO 3166 country codes. The upside of the file approach is that you could eventually map ISO 3166-2 subdivision codes to files in the event that there really is something like "this place only matters for Arizona or South Australia".

2. The most minimal version of this would be to just do the suffixing on your end. If most of your users are in the US, I could see this working for now. As long as we can search and get results, we could deal.

3. Instead of preferred region, I think I'd suggest adding UI that allows the user to pick which countries you show restaurant data from. I'm in Canada like 95% of the time. But, I was just travelling in the US and ate at Shake Shack. Because there's locations where I'm never near, I think you'd get better search results by filtering out places like Australia instead of just sorting. Could be wrong about the impact there though.

4. For convenience, you could geolocate. I don't think you want to do GPS location because of privacy concerns, which means what's left is IP based, which would be _ok_ for grabbing a high level location that you could use to get a subdivision. It won't always be accurate though, so if you went that route, you might want to do sorting instead of filtering. I'm iffy about if this is worth it, and it's always something you can add later if we're properly giving you location data for the restaurants.

I guess one other question here is also if you want to do some kind of location thing for foods with a barcode. I've been scanning a lot of President's Choice stuff which doesn't exist in the US (as far as I know). At that point, it might actually be worth grabbing a rough location...

**Comment by benjohnson** [comment]
Closing this until we've got a more robust way to handle this.

**Comment by ryanashcraft** [comment]
Appreciate you all chiming in here with suggestions! @benjohnson I think your option 3, combined with a reasonable default based on IP or device region makes sense. I don't have the capacity right now to take this on – it would be a decent amount of effort. For the time being, I'm totally fine just prefixing as necessary. I think in Tim Horton's case, I won't prefix until someone complains.
