### ISSUE TITLE
How should values like "less  than 1  gram" be coded?

### ISSUE THREAD

**Issue by danli-ds** [ryanashcraft/restaurant-nutrition-data#8]
There are text values for some data like "less  than 1  gram" and "<5". How should we recode these into numeric values? Thanks!

**Comment by danli-ds** [comment]
I found the answer in five guys' data. It's coded as `<1` and I will follow the convention.

**Comment by ryanashcraft** [comment]
@danli-ds Yes, exactly. The '<' is removed when parsing.
